baseURL = 'https://blog.xlau.uk/'
languageCode = 'en-us'
title = "Kylexlau's Weblog"
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Kylexlau's Weblog, a simple tech blog."

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
# homeIntroTitle = 'Hi!'
homeIntroContent = """
*Ars longa, vita brevis*\n
*The lyf so short, the craft so long to lerne*\n
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 10
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
#[[params.social]]
#name = "linkedin"
#url = "https://www.linkedin.com/in/user/"

[[params.social]]
name = "twitter"
url = "https://x.com/kylexlau"

[[params.social]]
name = "github"
url = "https://github.com/kylexlau"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'
